name: kids_bank_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  crop_your_image: ^2.0.0
  draw_your_image: ^0.12.0
  flutter_neumorphic_plus: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
